# Generated by Django 3.0.8 on 2020-11-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('Normal Process', 'Normal Process'), ('Fast Process', 'Fast Process')], default='Normal Process', help_text='Task Priority Status', max_length=100)),
                ('date_task_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('expected_completion_date', models.DateField(verbose_name='Expected Completion Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='employee.Employees', verbose_name='Assigned To')),
            ],
            options={
                'verbose_name': 'Task Profile',
                'verbose_name_plural': 'Tasks Profile',
                'ordering': ('created_date',),
            },
        ),
    ]
