# Generated by Django 3.0.8 on 2020-11-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201104_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference'),
        ),
    ]
